server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://127.0.0.1:3306/henglong?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver


logging:
  level:
    com:
      chl:
        applet:
          dao:  debug

#自定义属性
upload-dir: D:\Apache Software Foundation\Tomcat 9.0\webapps\img
img-url: http://localhost/img
web-url: http://localhost:8080/ed/
asset-url: http://localhost:8080/handover_order/